name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
        
    - name: publish
      run: |
        cd WebApp
        dotnet publish -c release
      
    - name: Change base-tag in index.html from / to the necessary
      run: sed -i "s/<base href=\"\/\" \/>/<base href=\"\/$(basename $(pwd))\/\" \/>/g" ./WebApp/bin/release/net5.0/publish/wwwroot/index.html
      
    - name: Add .nojekyll file
      run: touch ./WebApp/bin/release/net5.0/publish/wwwroot/.nojekyll
      
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      name: gh-pages publish
      with:
        branch: gh-pages
        folder: ./WebApp/bin/release/net5.0/publish/wwwroot
